name: Test

on:
    push:
        branches: [ "main" ]
        tags: [ "*" ]
    pull_request:
        branches: [ "main" ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3

            -   name: Install rust
                uses: dtolnay/rust-toolchain@stable
                with:
                    components: rustfmt

            -   name: Check format
                run: cargo fmt --check

            -   name: Test
                run: cargo test
